#!/usr/bin/env python3
"""Run one KPolaris slow-light image from an on-demand DDC fluid window."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
import time
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from dense_dump_codec.kpolaris_service import request_ddc_frame, shutdown_ddc_server
from dense_dump_codec.sequence import DenseSequenceIndex
from dense_dump_codec.kpolaris_parameters import (
    FILE_KEYS, automatic_radius, batch_output_paths, normalize_key, radial_request, verify_effective_radius,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--kpolaris-binary", type=Path, required=True)
    parser.add_argument("--parameter-file", type=Path, required=True)
    parser.add_argument("--observation-time", type=float, required=True)
    parser.add_argument("--fluid-time-min", type=float, required=True)
    parser.add_argument("--fluid-time-max", type=float, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--cache-dir", type=Path)
    parser.add_argument(
        "--materializer",
        type=Path,
        default=PROJECT_ROOT / "scripts" / "materialize_ddc_for_kpolaris.py",
    )
    parser.add_argument(
        "--server",
        type=Path,
        default=PROJECT_ROOT / "scripts" / "serve_ddc_for_kpolaris.py",
    )
    parser.add_argument("--socket-path", type=Path)
    parser.add_argument("--server-start-timeout", type=float, default=30.0)
    parser.add_argument("--scheme")
    parser.add_argument("--datasets")
    parser.add_argument("--maximum-cache-files", type=int, default=4)
    parser.add_argument(
        "--prefetch-files",
        type=int,
        default=1,
        help="Native aligned decode-batch size used by the persistent DDC service.",
    )
    parser.add_argument("--native-decode-workers", type=int, default=4)
    parser.add_argument("--native-archive-cache-chunks", type=int, default=128)
    parser.add_argument("--native-working-cache", type=Path)
    parser.add_argument("--native-transfer-mode", choices=("float32", "pinned", "compact"),
                        help="Opt-in host/GPU transfer backend; omitted preserves environment settings")
    parser.add_argument("--native-predictor-library", type=Path)
    parser.add_argument("--native-radius-max", type=radial_request,
                        help="Data ROI radius or auto to follow KPolaris outer_radius; requires serve_ddc_native.py")
    parser.add_argument(
        "--transport",
        choices=("native", "phdf"),
        default="native",
        help="Use direct staged arrays or the compatibility PHDF cache.",
    )
    parser.add_argument("--kpolaris-arg", action="append", default=[])
    parser.add_argument("--keep-cache", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_adapter_parameters(
    path: Path,
    *,
    frame_paths: list[Path],
    frame_times: list[float],
    observation_time: float,
) -> None:
    lines = [
        "# Generated by run_kpolaris_ddc_window.py",
        "model=kharma",
        f"kharma_dump={frame_paths[0]}",
        "slow_light=1",
        "slow_light_prefetch=1",
        f"slow_light_observation_time={observation_time:.17g}",
        f"slow_light_dump_list={','.join(map(str, frame_paths))}",
        f"slow_light_time_list={','.join(f'{time:.17g}' for time in frame_times)}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_command(
    binary: Path,
    parameter_file: Path,
    adapter_parameters: Path,
    output: Path,
    extra_args: list[str],
) -> list[str]:
    return [
        str(binary),
        f"--parameter_file={parameter_file}",
        f"--parameter_file={adapter_parameters}",
        f"--output={output}",
        f"--parameter_output={output}.params",
        *extra_args,
    ]


def validate_radial_region(radius, transport, server, parameter_file, extra_args):
    """Fail closed unless the explicitly selected data ROI covers the radiation cutoff."""
    if radius is None:
        return
    if not math.isfinite(radius) or radius <= 0 or transport != "native":
        raise ValueError("Radial ROI requires a positive finite radius and native transport")
    if server.resolve() != (PROJECT_ROOT / "scripts/serve_ddc_native.py").resolve():
        raise ValueError("Radial ROI requires the owned serve_ddc_native.py service")
    if any(normalize_key(argument.split("=", 1)[0]) in FILE_KEYS for argument in extra_args):
        raise ValueError("Use automatic ROI when additional KPolaris parameter files are supplied")
    outer_radius = automatic_radius(parameter_file, extra_args)
    if (outer_radius is None or not math.isfinite(outer_radius)
            or outer_radius <= 0 or outer_radius > radius):
        raise ValueError("Radial data ROI must cover an explicit, positive GRRT outer_radius")


def main() -> int:
    args = parse_args()
    transfer_mode = args.native_transfer_mode
    if transfer_mode is None:
        transfer_mode = "compact" if os.environ.get("KPOLARIS_DDC_COMPACT") == "1" else (
            "pinned" if os.environ.get("KPOLARIS_DDC_PINNED") == "1" else "float32")
    if transfer_mode != "float32" and (args.transport != "native" or
            args.server.resolve() != (PROJECT_ROOT / "scripts/serve_ddc_native.py").resolve()):
        raise ValueError("Optimized transfer requires the owned native DDC service")
    if transfer_mode == "compact":
        if args.native_working_cache is None:
            raise ValueError("Compact transfer requires the spatial working cache")
        args.native_predictor_library = None
    radius_policy = args.native_radius_max
    if radius_policy == "auto":
        if args.transport != "native" or args.server.resolve() != (PROJECT_ROOT / "scripts/serve_ddc_native.py").resolve():
            raise ValueError("Automatic ROI requires the owned native DDC service")
        args.native_radius_max = automatic_radius(args.parameter_file, args.kpolaris_arg)
    else:
        validate_radial_region(args.native_radius_max, args.transport, args.server,
                               args.parameter_file, args.kpolaris_arg)
    if args.native_predictor_library is not None and (args.transport != "native" or
            args.server.resolve() != (PROJECT_ROOT / "scripts/serve_ddc_native.py").resolve()):
        raise ValueError("Native prediction kernel requires the owned native DDC service")
    if args.native_working_cache is not None and (args.transport != "native" or
            args.server.resolve() != (PROJECT_ROOT / "scripts/serve_ddc_native.py").resolve()):
        raise ValueError("Spatial working cache requires the owned native DDC service")
    if args.native_radius_max is not None and any(normalize_key(argument.split("=", 1)[0]) in {
            "parameter_output", "params_output", "effective_parameters", "effective_parameter_file"}
            for argument in args.kpolaris_arg):
        raise ValueError("ROI verification requires the launcher's KPolaris parameter output path")
    radius_outputs = (batch_output_paths(args.parameter_file, args.kpolaris_arg) or [args.output.resolve()]) if args.native_radius_max is not None else []
    if args.maximum_cache_files < 3:
        raise ValueError("maximum-cache-files must be at least 3 for asynchronous prefetch")
    if args.prefetch_files < 1:
        raise ValueError("prefetch-files must be positive")
    if args.prefetch_files > args.maximum_cache_files:
        raise ValueError("prefetch-files cannot exceed maximum-cache-files")
    index = DenseSequenceIndex.from_manifest(args.manifest)
    frames = index.covering_range(args.fluid_time_min, args.fluid_time_max)
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    cache_dir = (
        args.cache_dir.resolve()
        if args.cache_dir is not None
        else output.parent / ".ddc-cache" / output.stem
    )
    socket_token = hashlib.sha256(str(output).encode("utf-8")).hexdigest()[:12]
    socket_path = (
        args.socket_path.resolve()
        if args.socket_path is not None
        else Path(tempfile.gettempdir())
        / f"kpolaris-ddc-{os.getpid()}-{socket_token}.sock"
    )
    server_ready = Path(f"{output}.ddc-server.ready.json")
    server_stats = Path(f"{output}.ddc-server.json")
    server_log = Path(f"{output}.ddc-server.log")
    frame_paths = [cache_dir / f"ddc_frame_{frame.sequence:05d}.phdf" for frame in frames]
    adapter_parameters = Path(f"{output}.ddc.par")
    write_adapter_parameters(
        adapter_parameters,
        frame_paths=frame_paths,
        frame_times=[frame.time for frame in frames],
        observation_time=args.observation_time,
    )
    command = build_command(
        args.kpolaris_binary.resolve(),
        args.parameter_file.resolve(),
        adapter_parameters,
        output,
        args.kpolaris_arg,
    )
    environment = os.environ.copy()
    environment["KPOLARIS_DDC_PINNED"] = str(int(transfer_mode == "pinned"))
    environment["KPOLARIS_DDC_COMPACT"] = str(int(transfer_mode == "compact"))
    environment.update(
        {
            "KPOLARIS_DDC_MANIFEST": str(args.manifest.resolve()),
            "KPOLARIS_DDC_MATERIALIZER": str(args.materializer.resolve()),
            "KPOLARIS_DDC_PYTHON": sys.executable,
            "KPOLARIS_DDC_MAXIMUM_CACHE_FILES": str(args.maximum_cache_files),
            "KPOLARIS_DDC_SOCKET": str(socket_path),
            "KPOLARIS_DDC_NATIVE": "1" if args.transport == "native" else "0",
        }
    )
    if args.scheme:
        environment["KPOLARIS_DDC_SCHEME"] = args.scheme
    if args.datasets:
        environment["KPOLARIS_DDC_DATASETS"] = args.datasets

    report_path = Path(f"{output}.ddc-run.json")
    report = {
        "format": "kpolaris_ddc_window_v2",
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "manifest": str(args.manifest.resolve()),
        "manifest_sha256": sha256(args.manifest),
        "kpolaris_binary": str(args.kpolaris_binary.resolve()),
        "kpolaris_binary_sha256": (
            sha256(args.kpolaris_binary) if args.kpolaris_binary.is_file() else None
        ),
        "parameter_file": str(args.parameter_file.resolve()),
        "parameter_file_sha256": (
            sha256(args.parameter_file) if args.parameter_file.is_file() else None
        ),
        "observation_time": args.observation_time,
        "fluid_time_min": args.fluid_time_min,
        "fluid_time_max": args.fluid_time_max,
        "selected_frames": [
            {**frame.to_json(), "materialized_path": str(path)}
            for frame, path in zip(frames, frame_paths, strict=True)
        ],
        "maximum_cache_files": args.maximum_cache_files,
        "prefetch_files": args.prefetch_files,
        "native_decode_workers": args.native_decode_workers,
        "native_archive_cache_chunks": args.native_archive_cache_chunks,
        "native_radius_max": args.native_radius_max,
        "native_radius_policy": radius_policy,
        "native_working_cache": str(args.native_working_cache) if args.native_working_cache else None,
        "initial_prefetch_sequences": [
            frame.sequence for frame in frames[: args.maximum_cache_files]
        ],
        "cache_dir": str(cache_dir),
        "adapter_backend": (
            "native_staged_array_socket"
            if args.transport == "native"
            else "persistent_phdf_socket"
        ),
        "transport": args.transport,
        "native_transfer_mode": transfer_mode,
        "socket_path": str(socket_path),
        "server_log": str(server_log),
        "server_stats": str(server_stats),
        "keep_cache": args.keep_cache,
        "command": command,
        "adapter_environment": {
            key: value
            for key, value in environment.items()
            if key.startswith("KPOLARIS_DDC_")
        },
        "dry_run": args.dry_run,
        "returncode": None,
    }
    server_command = [
        sys.executable,
        str(args.server.resolve()),
        "--manifest",
        str(args.manifest.resolve()),
        "--socket",
        str(socket_path),
        "--cache-dir",
        str(cache_dir),
        "--maximum-cache-files",
        str(args.maximum_cache_files),
        "--prefetch-files",
        str(args.prefetch_files),
        "--native-decode-workers",
        str(args.native_decode_workers),
        "--native-archive-cache-chunks",
        str(args.native_archive_cache_chunks),
        "--ready-file",
        str(server_ready),
        "--stats-file",
        str(server_stats),
    ]
    if args.scheme:
        server_command.extend(["--scheme", args.scheme])
    if args.datasets:
        server_command.extend(["--datasets", args.datasets])
    if args.native_radius_max is not None:
        server_command.extend(["--native-radius-max", str(args.native_radius_max)])
    if args.native_working_cache is not None:
        server_command.extend(["--native-working-cache", str(args.native_working_cache.resolve())])
    if args.native_predictor_library is not None:
        library = args.native_predictor_library.resolve(strict=True)
        server_command.extend(["--native-predictor-library", str(library)])
        report["native_predictor_library"] = str(library)
        report["native_predictor_sha256"] = sha256(library)
    report["server_command"] = server_command
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    if args.dry_run:
        print(json.dumps(report, indent=2, sort_keys=True))
        return 0

    socket_path.unlink(missing_ok=True)
    server_ready.unlink(missing_ok=True)
    server_stats.unlink(missing_ok=True)
    server_log.parent.mkdir(parents=True, exist_ok=True)
    server_process: subprocess.Popen | None = None
    server_log_handle = server_log.open("w", encoding="utf-8")
    try:
        server_process = subprocess.Popen(
            server_command,
            env=environment,
            stdout=server_log_handle,
            stderr=subprocess.STDOUT,
            text=True,
        )
        deadline = time.monotonic() + args.server_start_timeout
        while not server_ready.is_file() or not socket_path.exists():
            returncode = server_process.poll()
            if returncode is not None:
                raise RuntimeError(
                    f"DDC service exited with return code {returncode}; see {server_log}"
                )
            if time.monotonic() >= deadline:
                raise TimeoutError(
                    f"DDC service was not ready after {args.server_start_timeout:g}s"
                )
            time.sleep(0.05)
        if args.transport == "phdf":
            request_ddc_frame(socket_path, frames[0].sequence)
        result = subprocess.run(command, env=environment, check=False)
        report["returncode"] = result.returncode
        if result.returncode == 0 and args.native_radius_max is not None:
            try:
                for destination in radius_outputs:
                    verify_effective_radius(Path(f"{destination}.params"), args.native_radius_max)
            except (OSError, KeyError, ValueError) as error:
                report["returncode"] = 1
                report["native_radius_validation_error"] = str(error)
                raise
            report["native_radius_verified_against_kpolaris"] = True
            report["native_radius_verified_outputs"] = list(map(str, radius_outputs))
        report["finished_at_utc"] = datetime.now(UTC).isoformat()
    finally:
        if server_process is not None and server_process.poll() is None:
            try:
                shutdown_ddc_server(socket_path)
            except (OSError, RuntimeError):
                server_process.terminate()
            try:
                server_process.wait(timeout=30.0)
            except subprocess.TimeoutExpired:
                server_process.kill()
                server_process.wait()
        server_log_handle.close()
        socket_path.unlink(missing_ok=True)
        server_ready.unlink(missing_ok=True)
        if server_stats.is_file():
            report["service_statistics"] = json.loads(
                server_stats.read_text(encoding="utf-8")
            )
        report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
        if not args.keep_cache:
            shutil.rmtree(cache_dir, ignore_errors=True)
    return int(report["returncode"])


if __name__ == "__main__":
    raise SystemExit(main())
