#!/usr/bin/env python3
"""Run one KPolaris slow-light image from retained raw KHARMA PHDF files."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from dense_dump_codec.raw_sequence import load_raw_sequence_index


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--dense-sequence-stride", type=int, required=True)
    parser.add_argument("--index-cache", type=Path)
    parser.add_argument("--kpolaris-binary", type=Path, required=True)
    parser.add_argument("--parameter-file", type=Path, required=True)
    parser.add_argument("--observation-time", type=float, required=True)
    parser.add_argument("--fluid-time-min", type=float, required=True)
    parser.add_argument("--fluid-time-max", type=float, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--kpolaris-arg", action="append", default=[])
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(16 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_adapter_parameters(
    path: Path,
    *,
    frame_paths: list[Path],
    frame_times: list[float],
    observation_time: float,
) -> None:
    lines = [
        "# Generated by run_kpolaris_raw_window.py",
        "model=kharma",
        f"kharma_dump={frame_paths[0]}",
        "slow_light=1",
        "slow_light_prefetch=1",
        f"slow_light_observation_time={observation_time:.17g}",
        f"slow_light_dump_list={','.join(map(str, frame_paths))}",
        f"slow_light_time_list={','.join(f'{time:.17g}' for time in frame_times)}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    input_dir = args.input_dir.resolve()
    index_cache = (
        args.index_cache.resolve()
        if args.index_cache is not None
        else input_dir / f"raw_sequence_stride{args.dense_sequence_stride}.json"
    )
    index, index_payload, index_reused = load_raw_sequence_index(
        input_dir,
        dense_sequence_stride=args.dense_sequence_stride,
        cache_path=index_cache,
    )
    frames = index.covering_range(args.fluid_time_min, args.fluid_time_max)
    frame_paths = [Path(frame.path) for frame in frames]
    adapter_parameters = Path(f"{output}.raw.par")
    write_adapter_parameters(
        adapter_parameters,
        frame_paths=frame_paths,
        frame_times=[frame.time for frame in frames],
        observation_time=args.observation_time,
    )
    command = [
        str(args.kpolaris_binary.resolve()),
        f"--parameter_file={args.parameter_file.resolve()}",
        f"--parameter_file={adapter_parameters}",
        f"--output={output}",
        f"--parameter_output={output}.params",
        *args.kpolaris_arg,
    ]
    report = {
        "format": "kpolaris_raw_window_v1",
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "input_dir": str(input_dir),
        "dense_sequence_stride": args.dense_sequence_stride,
        "index_cache": str(index_cache),
        "index_cache_sha256": sha256(index_cache),
        "index_reused": index_reused,
        "index_frame_count": index_payload["frame_count"],
        "kpolaris_binary": str(args.kpolaris_binary.resolve()),
        "kpolaris_binary_sha256": (
            sha256(args.kpolaris_binary) if args.kpolaris_binary.is_file() else None
        ),
        "parameter_file": str(args.parameter_file.resolve()),
        "parameter_file_sha256": (
            sha256(args.parameter_file) if args.parameter_file.is_file() else None
        ),
        "observation_time": args.observation_time,
        "fluid_time_min": args.fluid_time_min,
        "fluid_time_max": args.fluid_time_max,
        "selected_frames": [frame.to_json() for frame in frames],
        "command": command,
        "dry_run": args.dry_run,
        "returncode": None,
    }
    report_path = Path(f"{output}.raw-run.json")
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    if args.dry_run:
        print(json.dumps(report, indent=2, sort_keys=True))
        return 0
    result = subprocess.run(command, check=False)
    report["returncode"] = result.returncode
    report["finished_at_utc"] = datetime.now(UTC).isoformat()
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
